GOOGLE_CLOUD_PROJECT = YOUR_PROJECT_ID
EMAIL_SERVICE_URL = $(shell gcloud run services describe email-service --platform managed --region us-east1 --format="value(status.address.url)")
PROJECT_NUMBER = 404041649990

submit:
	gcloud builds submit --tag gcr.io/$(GOOGLE_CLOUD_PROJECT)/email-service

deploy:
	gcloud run deploy email-service \
	--image gcr.io/$(GOOGLE_CLOUD_PROJECT)/email-service \
	--platform managed \
	--region us-east1 \
	--allow-unauthenticated \
	--max-instances=1

generate-sac:
	gcloud iam service-accounts create pubsub-cloud-run-invoker --display-name "PubSub Cloud Run Invoker"

give-sac:
	gcloud run services add-iam-policy-binding email-service --member=serviceAccount:pubsub-cloud-run-invoker@$(GOOGLE_CLOUD_PROJECT).iam.gserviceaccount.com --role=roles/run.invoker --region us-east1 --platform managed

give-token-creator:
	gcloud projects add-iam-policy-binding $(GOOGLE_CLOUD_PROJECT) --member=serviceAccount:service-$(PROJECT_NUMBER)@gcp-sa-pubsub.iam.gserviceaccount.com --role=roles/iam.serviceAccountTokenCreator

create-email-subscriber:
	gcloud pubsub subscriptions create email-service-sub --topic new-lab-report --push-endpoint=$(EMAIL_SERVICE_URL) --push-auth-service-account=pubsub-cloud-run-invoker@$(GOOGLE_CLOUD_PROJECT).iam.gserviceaccount.com

