GOOGLE_CLOUD_PROJECT = YOUR_PROJECT_ID
SMS_SERVICE_URL=$(shell gcloud run services describe sms-service --platform managed --region us-east1 --format="value(status.address.url)")

submit:
	gcloud builds submit --tag gcr.io/$(GOOGLE_CLOUD_PROJECT)/sms-service

deploy:
	gcloud run deploy sms-service \
	--image gcr.io/$(GOOGLE_CLOUD_PROJECT)/sms-service \
	--platform managed \
	--region us-east1 \
	--allow-unauthenticated \
	--max-instances=1

exec:
	make submit
	make deploy

give-sac:
	gcloud run services add-iam-policy-binding sms-service --member=serviceAccount:pubsub-cloud-run-invoker@$(GOOGLE_CLOUD_PROJECT).iam.gserviceaccount.com --role=roles/run.invoker --region us-east1 --platform managed

create-sms-subscriber:
	gcloud pubsub subscriptions create sms-service-sub --topic new-lab-report --push-endpoint=$(SMS_SERVICE_URL) --push-auth-service-account=pubsub-cloud-run-invoker@$(GOOGLE_CLOUD_PROJECT).iam.gserviceaccount.com